Models/Contrato.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace sistema_inmobiliaria_ulp_2025.Models;

public class Contrato
{
    public Contrato() { }
    [Key]
    public int Id { get; set; }
    public DateOnly Desde { get; set; }
    public DateOnly Hasta { get; set; }

    [ForeignKey("Inquilino")]
    public int InquilinoId { get; set; }
    public virtual required Inquilino? Inquilino { get; set; }

    [ForeignKey("Inmueble")]
    public int InmuebleId { get; set; }
    public virtual required Inmueble? Inmueble { get; set; }

    [InverseProperty("Contrato")]
    public virtual required List<Pago>? Pagos { get; set; }

}

Models/DatosPersonales.cs
 namespace sistema_inmobiliaria_ulp_2025.Models;

public class DatosPersonales
{
    protected string? DNI { get; set; }
    protected string? Apellido { get; set; }
    protected string? Nombre { get; set; }
    protected string? Email { get; set; }
    protected string? Telefono { get; set; }


 }

Models/ErrorViewModel.cs
/*namespace es nombre asignado para un grupo de archivos.
es un nombre de espcio que funciona como contenedor absracto que agrupa 
identificadores únicos como clases, funciones y variables permitiendo que
 el mismo nombre se utilicen en diferentes contextos sin conflictos*/
 namespace sistema_inmobiliaria_ulp_2025.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }
    
    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/Inmueble.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace sistema_inmobiliaria_ulp_2025.Models;

public class Inmueble
{
    public Inmueble() { }
    [Key]
    public int Id { get; set; }
    [ForeignKey("Propietario")]
    public int PropietarioId { get; set; }
    public virtual required Propietario? Propietario { get; set; }
    public string Direccion { get; set; } = "";
    public Uso Uso { get; set; }
    public Tipo Tipo { get; set; }
    public int NumeroAmbientes { get; set; }
    public double Latitud { get; set; }
    public double Longitud { get; set; }
    public decimal Precio { get; set; }
    public Disponibilidad Disponibilidad { get; set; }
 }
public enum Uso
{
    COMERCIAL,
    RESIDENCIA,
}
public enum Tipo
{
    LOCAL,
    DEPOSITO,
    CASA,
    DEPARTAMENTO,
}
public enum Disponibilidad
{
    OCUPADO,
    SUSPENDIDO,
    DESOCUPADO,
}

Models/Inquilino.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace sistema_inmobiliaria_ulp_2025.Models;

public class Inquilino : DatosPersonales
{
    public Inquilino() { }

    [Key]
    public int Id { get; set; }

    [InverseProperty("Inquilino")]
    public virtual required List<Contrato>? Contratos { get; set; }

}

 

Models/Pago.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace sistema_inmobiliaria_ulp_2025.Models;


public class Pago
{
    public Pago() { }

    [Key]
    public int Id { get; set; }
    public int NoPago { get; set; }
    public DateOnly Fecha { get; set; }
    public decimal Importe { get; set; }

    [ForeignKey("Contrato")]
    public int ContratoId { get; set; }
    public virtual required Contrato? Contrato { get; set; }

    [ForeignKey("Inquilino")]
    public int InquilinoId { get; set; }
    public virtual required Inquilino? Inquilino { get; set; }
};

Models/Propietario.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace sistema_inmobiliaria_ulp_2025.Models;

public class Propietario : DatosPersonales
{
    public Propietario() { }
    [Key]
    private int Id { get; set; }
    [InverseProperty("Propietario")]
    public virtual required List<Inmueble>? Inmueble { get; set; }
}

Models/User.cs
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Runtime.CompilerServices;
using MySqlConnector;
namespace sistema_inmobiliaria_ulp_2025.Models;

public class User
{
    public User() { }
    public User(MySqlDataReader reader)
    {
        Id = reader.GetInt32("Id");
        Username = reader.GetString("Username");
        Password = reader.GetString("Password");
        Rol = reader.GetString("Rol");
    }

    public User(int id, string username, string password, string rol)
    {
        Id = id;
        Username = username;
        Password = password;
        Rol = rol;
    }

    [Key]
    public int Id { get; set; }
    public string Username { get; set; } = "";
    public string Password { get; set; } = "";
    public string Rol { get; set; } = "";
}

Controllers/CuentaController.cs
using System.Security.Claims;
using sistema_inmobiliaria_ulp_2025.Models;
using sistema_inmobiliaria_ulp_2025.Repositories.Interfaces;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;

namespace sistema_inmobiliaria_ulp_2025.Controllers;

public class CuentaController : Controller
{
    private readonly IUserRepository _userRepository;

    public CuentaController(IUserRepository userRepository)
    {
        _userRepository = userRepository;
    }

    [HttpPost]
    public async Task<IActionResult> Registrar([FromBody] User user)
    {
        user.Password = BCrypt.Net.BCrypt.HashPassword(user.Password);
        await _userRepository.AddAsync(user);
        await _userRepository.SaveAsync();

        return Ok(new { message = "Completado con éxito." });
    }

    [HttpGet]
    public IActionResult IniciarSesion()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> IniciarSesion([FromForm] User user)
    {
        User? usuarioEnDB = await _userRepository.GetByUsernameAsync(user.Username);

        if (usuarioEnDB == null || !BCrypt.Net.BCrypt.Verify(user.Password, usuarioEnDB.Password))
        {
            ModelState.AddModelError("", "Usuario o Contraseña incorrectos.");
            return View();
        }

        var claims = new List<Claim>
        {
            new Claim(ClaimTypes.Name, usuarioEnDB.Username),
            new Claim(ClaimTypes.Role, usuarioEnDB.Rol),
        };

        var identity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
        var principal = new ClaimsPrincipal(identity);

        await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal);
        return RedirectToAction("Index", "Home");
    }

    [HttpGet]
    public IActionResult CerrarSesion()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> _CerrarSesion()
    {
        await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
        return RedirectToAction("IniciarSesion");
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using sistema_inmobiliaria_ulp_2025.Models;
using Microsoft.AspNetCore.Mvc;

namespace Inmobiliaria.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(
            new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier }
        );
    }
}

Views/Cuenta/CerrarSesion.cshtml
@{
    Layout = "_Autenticacion";
    ViewData["Title"] = "CERRAR SESIÓN";
}

<form class="container-fluid d-flex p-2 justify-content-center align-items-center" asp-action="_CerrarSesion"
    method="post">
    <fieldset class="border border-danger rounded fw-bold px-2 shadow bg-secondary">
        <legend class="text-center my-3">¿Deseas cerrar sesión?</legend>
        <div class="d-flex justify-content-between align-items-center my-3">
            <button type="submit" class="btn btn-danger border border-white text-white mx-1">
                CERRAR SESIÓN
            </button>
            <button asp-controller="Home" asp-action="Index" class="btn btn-dark border border-white text-white mx-1">
                VOLVER ATRAS
            </button>
        </div>
    </fieldset>
</form>

Views/Cuenta/IniciarSesion.cshtml
@model User
@{
    Layout = "_Autenticacion";
    ViewData["Title"] = "INICIAR SESIÓN";
}
@if (!ViewData.ModelState.IsValid)
{
    <div class="alert alert-danger">
        @Html.ValidationSummary(false)
    </div>
}
<form class="container-fluid d-flex flex-column justify-content-center align-items-center fw-bold"
    asp-controller="Cuenta" asp-action="IniciarSesion" method="post">
    <fieldset class="border border-primary rounded w-33 mb-3 px-3 shadow bg-secondary">
        <legend class="text-center mt-3">INICIAR SESIÓN</legend>
        <label for="username" class="my-3">Usuario</label>
        <input placeholder="Usuario" class="form-control my-3" type="text" asp-for="Username" id="username">
        <label for="password" class="my-3">Contraseña</label>
        <input placeholder="Contraseña" class="form-control mb-3" type="password" asp-for="Password" id="password">
    </fieldset>
    <button type="submit" class="btn btn-success text-white">INICIAR SESIÓN</button>
</form>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "INICIO";
}

<div class="text-center">
    <h1 class="display-4">Bienvenidos</h1>
    <p>Seleccione lo que desea ver en la barra superior.</p>
</div>

Views/Shared/_Autenticacion.cshtml
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewData["Title"] - Inmobiliaria</title>
    <link rel="preconnect" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <script defer src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
</head>

<body data-bs-theme="dark" class="d-flex flex-column vh-100 justify-content-between align-items-center">
    <header class="py-2 d-flex justify-content-center align-items-center">
        <h1 class="m-0">INMOBILIARIA</h1>
    </header>
    <main class="d-flex p-2 justify-content-center align-items-center">
        @RenderBody()
    </main>
    <footer class="py-2 d-flex justify-content-center align-items-center">
        <span class="text-muted m-0">&copy;; - 2025 | INMOBILIARIA</span>
    </footer>
</body>

</html>

Views/Shared/_Create.cshtml
@{
    ViewData["Title"] = "Crear";
    Layout = "_Layout";
}

<h4>Nuevo @ViewData["Cabecera"]</h4>
<hr class="bg-light h-2 w-25 shadow" />
<div asp-validation-summary="ModelOnly" class="text-danger"></div>

<form asp-action="Create" class="border border-info d-flex flex-column p-2" method="post">
    <div asp-validation-summary="ModelOnly" class="text-danger w-100"></div>
    @RenderBody()
    <button type="submit" class="btn btn-primary">Crear</button>
</form>
<div>
    <a asp-action="Index" class="btn btn-danger border border-white mt-2">Volver a la lista</a>
</div>

Views/Shared/_Delete.cshtml
@{
    ViewData["Title"] = "Eliminar";
    Layout = "_Layout";
}

<h3>¿Quieres eliminar esto?</h3>
<div>
    <h4>@ViewData["Sector"]</h4>
    <hr />
    <dl class="row dl-horizontal">
        @await RenderSectionAsync("Datos_dl", required: true)
    </dl>

    <form asp-action="Delete">
        @await RenderSectionAsync("Input_Id", required: true)
        <button type="submit" class="btn btn-danger">Eliminar</button> |
        <a asp-action="Index">Volver al listado</a>
    </form>
</div>

Views/Shared/_Details.cshtml
@{
    ViewData["Title"] = "Detalles";
    Layout = "_Layout";
}

<div>
    <h4>@ViewData["Sector"]</h4>
    <hr />
    <dl class="row dl-horizontal">
        @await RenderSectionAsync("Datos_dl", required: true)
    </dl>
</div>
<div>
    @await RenderSectionAsync("a_action_edit", required: true) |
    <a asp-action="Index">Volver al listado</a>
</div>

Views/Shared/_Edit.cshtml
@{
    ViewData["Title"] = "Editar";
    Layout = "_Layout";
}

<h4>@ViewData["Sector"]</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            @await RenderSectionAsync("errors_and_id", required: true)
            @RenderBody()
            <button type="submit" class="btn btn-primary">Guardar</button>
        </form>
    </div>
</div>
<div>
    <a asp-action="Index">Volver al listado</a>
</div>

Views/Shared/_Index.cshtml
@{
    ViewData["Title"] = "Listado";
    Layout = "_Layout";
}

<div class="container-fluid d-flex justify-content-evenly align-items-center">
    <a asp-action="Create" class="btn btn-secondary border border-white rounded fw-bold">
        Crear nuevo
    </a>
    @await RenderSectionAsync("FormFiltros", required: false)
</div>

<table class="table">
    <thead>
        <tr>
            @await RenderSectionAsync("TableHeaders", required: true)
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
        @await RenderSectionAsync("TableBody", required: true)
    </tbody>
</table>

Views/Shared/_Layout.cshtml
@{
    var controlador = ViewContext.RouteData.Values["controller"]?.ToString();
    var accion = ViewContext.RouteData.Values["action"]?.ToString();
}
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Inmobiliaria</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Inmobiliaria.styles.css" asp-append-version="true" />
</head>

<body data-bs-theme="dark" class="vh-100 vw-100 m-0 p-0 d-flex flex-column justify-content-between align-items-center">
    <header class="container-fluid">
        <nav
            class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-black border-bottom box-shadow mb-3 text-white">
            <div class="container-fluid">
                <a class="navbar-brand fw-bold" asp-area="" asp-controller="Home" asp-action="Index">INMOBILIARIA</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul id="header_top_bar" class="navbar-nav flex-grow-1">
                        <li
                            class="nav-item align-items-center @(controlador == "Home" && accion == "Index" ? "border border-white" : "")">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">
                                Inicio
                            </a>
                        </li>
                        <li
                            class="nav-item align-items-center @(controlador == "Inmueble" && accion == "Index" ? "border border-white" : "")">
                            <a class="nav-link text-white" asp-area="" asp-controller="Inmueble" asp-action="Index">
                                Inmuebles
                            </a>
                        </li>
                        <li
                            class="nav-item align-items-center @(controlador == "Propietario" && accion == "Index" ? "border border-white" : "")">
                            <a class="nav-link text-white" asp-area="" asp-controller="Propietario" asp-action="Index">
                                Propietarios
                            </a>
                        </li>
                        <li
                            class="nav-item align-items-center @(controlador == "Inquilino" && accion == "Index" ? "border border-white" : "")">
                            <a class="nav-link text-white" asp-area="" asp-controller="Inquilino" asp-action="Index">
                                Inquilinos
                            </a>
                        </li>
                        <li
                            class="nav-item align-items-center @(controlador == "Contrato" && accion == "Index" ? "border border-white" : "")">
                            <a class="nav-link text-white" asp-route-filtro="fecha" asp-controller="Contrato"
                                asp-action="Index">
                                Contratos
                            </a>
                        </li>
                        <li
                            class="nav-item align-items-center @(controlador == "Pago" && accion == "Index" ? "border border-white" : "")">
                            <a class="nav-link text-white" asp-area="" asp-controller="Pago" asp-action="Index">
                                Pagos
                            </a>
                        </li>
                    </ul>
                    <a class="btn border border-danger" asp-controller="Cuenta" asp-action="CerrarSesion">CERRAR
                        SESIÓN</a>
                </div>
            </div>
        </nav>
    </header>
    <main role="main" class="h-100 container-fluid d-flex flex-column justify-content-start align-items-center">
        @RenderBody()
    </main>
    <footer class="border-top p-3 footer bg-black container-fluid text-center text-muted">
        &copy; 2025 - INMOBILIARIA
    </footer>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>